//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAC.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access
    {
        public int IdAccess { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<int> IdArea { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual User User { get; set; }
    }
}
